### PR TITLE
Added dictionary extension methods to get typed value 

### PR DESCRIPTION
**Pull request by gian8**

### CODE REVIEW

**Comment by EnricoMassoneDeltatre** [comment]
Hi @gian8,

first of all thanks for contributing to the library. Here is my comments: 
 - please include XML documentations to all the public methods: this greatly improve the usability of the library
 - please investigate the possibility to allow the caller to pass a parameter of type  IFormatProvider so that he or she is able to customize the culture specific aspects of the type conversion (this library is meant to be as general purpose as possible and should not force the caller to accept the current thread's culture when converting a value). You can refer to [this documentation from Microsoft](https://docs.microsoft.com/en-us/dotnet/api/system.convert.changetype?view=netframework-4.7.2#System_Convert_ChangeType_System_Object_System_Type_System_IFormatProvider_)

 - consider to throw an ArgumentNullException when parameter fields of method GetValueOrDefault is null. In my opinion calling this extension method on a null reference doesn't make  sense, in general i like to be strict with regards of null references. Of course, this is a matter of personal taste and I open to suggestions

**Comment by gian8** [comment]
Thanks for the comment @EnricoMassoneDeltatre 

I agree with you, I'm going to update it

**Comment by gian8** [comment]
@EnricoMassoneDeltatre 
We have updated with your previous suggestions.

For GetIntOrDefault() function I haven't added the IFormatProvider parameter in the signature, because I don't have in mind a practical scenario

**Comment by EnricoMassoneDeltatre** [comment]
Hi @gian8,

I guess we should add the additional parameter for the culture also with the method for integers.
As an example consider the following code: 

```
object myObject = "1.000"; // note that the string contains the thousands separator for italian culture
int myInteger = (int)Convert.ChangeType(myObject, typeof(int), new CultureInfo("it-IT")); // we expect to get 1000 as an integer
```
Actually the above code doesn't work ! This is an oddity that I decided to investigate (note that the CultureInfo class contains, among the other things, the information about the thousands separator so expecting the previous code to work seems reasonable). If you want to dig into this problem take a look at [this stackoverflow question](https://stackoverflow.com/questions/2400795/how-can-i-use-convert-changetype-to-convert-string-into-numerics-with-group-sepa). 

That said, I suggest to add the additional parameter even in the method GetIntOrDefault().
In a future release we can decide to modify the method GetValueOrDefault so that if the runtime type of source[key] is System.String and T is System.Int32 we can avoid using Convert.ChangeType and implement something custom able to support the thousands separator too (for instance we can decide to use int.TryParse which allows to pass a parameter for NumberStyles; [see NumberStyles.AllowThousands](https://docs.microsoft.com/it-it/dotnet/api/system.globalization.numberstyles?redirectedfrom=MSDN&view=netframework-4.7.2))
In order to do so, it is useful to have a parameter to allow the client to specify the culture and introducing it right now will prevent a future breaking change in the public api.

**Pull request merged**
